name:                fl2020-spbu-spr
version:             0.1.0.0
github:              "kajigor/fl-2020-spbu-spr"
license:             BSD3
author:              "Ekaterina Verbitskaia"
maintainer:          "kajigor@gmail.com"
copyright:           "2020 Ekaterina Verbitskaia"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://https://github.com/kajigor/fl-2020-spbu-spr>

dependencies:
- base >= 4.7 && < 5
- hedgehog
- HUnit
- tasty
- tasty-hedgehog
- tasty-hunit
- tasty-discover
- containers
- mtl

library:
  source-dirs: src

executables:
  expr:
    main:                Main.hs
    source-dirs:         app/expr
    dependencies:
    - fl2020-spbu-spr

tests:
  test:
    main:                Test.hs
    source-dirs:         test
    dependencies:
    - fl2020-spbu-spr
