name:                pparse
version:             0.1.0.0
license:             BSD3
author:              "Anton Shangareev"
maintainer:          "shananton2000@gmail.com"

extra-source-files:
  - README.md

dependencies:
  - base >= 4 && < 5

library:
  source-dirs: src
  exposed-modules:
    PLang
