name:                pparse
version:             0.1.0.0
license:             BSD3
author:              "Anton Shangareev"
maintainer:          "shananton2000@gmail.com"

extra-source-files:
  - README.md

dependencies:
  - base >= 4 && < 5
  - array

library:
  source-dirs: src
  exposed-modules:
    PLang
    LexP
    ParseP
  other-modules: []

executables:
  parser:
    main: Main.hs
    source-dirs: app
    dependencies:
      - pparse

tests:
  test:
    main: TestDriver.hs
    source-dirs: test
    dependencies:
      - pparse
      - tasty
      - tasty-hunit
      - tasty-discover
